name: Keep Workflows Alive

on:
  schedule:
    # Runs at 00:00 on the 1st of every month
    - cron: '0 0 1 * *'
  workflow_dispatch: # Allows you to trigger it manually if needed

jobs:
  keep_alive:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v1
